### PR TITLE
support enums in cockroachdb

### PR DESCRIPTION
**Pull request by wontruefree**

### CODE REVIEW

**Comment by matthewmcgarvey** [comment]
I would like to see an enum added or an enum modified (only if there's more than one so that Int32 and Int64 are covered) in specs. Just the process of adding it should reveal any edge cases we might have missed

**Review by jwoertink — CHANGES_REQUESTED** [review]
We should for sure add a spec to make sure this doesn't break anything. I'm thinking maybe we can adjust https://github.com/luckyframework/avram/blob/main/spec/support/models/issue.cr so that way one of these is default, and the other is Int64 like maybe `enum Status : Int64`, and migration would have to be setup for Int64 https://github.com/luckyframework/avram/blob/abdfbd51acb1d69c2ca482d582c145ea6e9cf37d/db/migrations/20200324211956_create_issue.cr#L5

Then in theory, this file https://github.com/luckyframework/avram/blob/main/spec/avram/type_extensions/enum_spec.cr should just all work.

**Comment by jwoertink** [comment]
Ok, so that theory worked... We can set the enum to Int64, and it seems to work.... Now the question is, do we have enough spec coverage to say with certainty that this won't break stuff? :joy:

**Comment by jwoertink** [comment]
This is actually done in https://github.com/luckyframework/avram/issues/825 So next release will support enums with Int64. I'll close this out now. Thanks @wontruefree!

**Pull request closed without merging**
