### PR TITLE
Add Float64 to ColumnType

### PR DESCRIPTION
**Pull request by brunto**
This is a solution for the issue: https://github.com/luckyframework/avram/issues/636

### CODE REVIEW

**Comment by matthewmcgarvey** [comment]
@brunto we're not going to remember why this type union was added. Could you add a spec that would fail before the change and this fixes?

**Review by jwoertink — APPROVED** [review]
Nice! Thanks for adding these specs. It's good to have them in.

**Comment by brunto** [comment]
It's not finished I have one more test to add.￼

**Comment by brunto** [comment]
Ok now I'm done.

**Comment by jwoertink** [comment]
@brunto now that you added that DOUBLE, I'm not sure if that type actually gets checked. I think it's just at runtime when you query on it, so you'd have to now add a spec that checks you can query on a DOUBLE column.

**Review by jwoertink — CHANGES_REQUESTED** [review]
I think the rest of it is fine. I'm not sure the best place to put the spec, but you can probably just add it [here](https://github.com/luckyframework/avram/blob/master/spec/queryable_spec.cr) and say that we can query float columns defined as `DOUBLE`.

**Comment by brunto** [comment]
@jwoertink I just saw the "bucket" table. Maybe it's better to put the "Double" columns inside Bucket instead of Business?

**Comment by jwoertink** [comment]
@brunto the buckets was used for Array stuff. I guess if you wanted to test a postgres array of double, then you can add an additional one there too, but otherwise what you have in business is fine.

**Comment by jwoertink** [comment]
Ok, I pulled this in to one of my projects, and it seems to work. @brunto if you get a sec, can you rebase to make sure everything is good?

**Comment by brunto** [comment]
I rebased the code but I have one more spec to push.

**Comment by brunto** [comment]
@jwoertink Ok all is good now.

**Review by jwoertink — APPROVED** [review]
woo hoo! Thanks for tackling this. 🎉

**Pull request merged**
