### PR TITLE
allow passing bind_args as array to Where::Raw

### PR DESCRIPTION
**Pull request by repomaa**
sometimes you might parse args from dynamic input so this enables you to do that.

### CODE REVIEW

**Comment by repomaa** [comment]
i forgot to add an overload for `Queryable#where`. That's added now.

**Comment by jwoertink** [comment]
Oh, good catch. I'll let this sit a bit just in case anyone else thinks of something that might be missing on this.

**Comment by repomaa** [comment]
I can also use `bind_vars` instead of `args` as variable name. I was just orientating from the way it's called in crystal-db.

**Comment by jwoertink** [comment]
Oh yeah, for sure. `args` is more intuitive than `bind_vars`.

**Pull request merged**
