### PR TITLE
v0.13.0

### PR DESCRIPTION
**Pull request by jwoertink**
This updates a few things:

* Avram to 0.13.0 with Crystal 0.33.0 support
* Use latest crystal-db
* Use latest crystal-pg

The new Docker container uses Ubuntu 18.04 (Bionic Beaver)

### CODE REVIEW

**Comment by paulcsmith** [comment]
If there are no breaking changes and it works in older versions of crystal could we do a patch release instead? So that this works with new lucky projects right away? That assume this really does work on crystal 0.32 which I think it does. Thoughts?

**Comment by jwoertink** [comment]
Hmm.. This is going to include all of the latest updates as well. Like features and bug fixes. I'm pretty sure it all works on 0.32, but I didn't try it out. Maybe I should just do a branch from the last release and then do a patch release instead?

**Comment by paulcsmith** [comment]
Yeah that’d a good idea. Branch of last release and cherry pick the fix should do it I think!

**Comment by jwoertink** [comment]
Ok, killing off this PR in favor of the next one as a patch release. I can do this release later after a few more PR are merged or whatever

**Pull request closed without merging**
